# Generated by Django 5.0 on 2023-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="authors", to="books.book"
            ),
        ),
    ]
